# docker compose up --build -d
# docker exec -it bf bash
version: "3.9"
services:
  bf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/bluefin/
    stdin_open: true
    tty: true
    working_dir: /usr/src/bluefin/build/
    image: bluefin:latest
    container_name: bf
