# docker compose up --build -d
# docker exec -it bf bash
version: "3.9"
volumes:
  boost:
services:
  bf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/bluefin/
      - boost:/usr/include/boost
    stdin_open: true
    tty: true
    working_dir: /usr/src/bluefin/
    image: bluefin:latest
    container_name: bf
